services:
  nginx:
    container_name: nginx
    healthcheck:
      interval: 60s
      retries: 5
      start_period: 10s
      test:
      - CMD
      - service
      - nginx
      - status
      timeout: 10s
    image: library/nginx:1.25.2
    network_mode: host
    restart: always
    volumes:
    - /opt/site/nginx/conf.d:/etc/nginx/conf.d:ro
    - /data/nginx/log:/var/log/nginx
    - /data/nginx/cache:/var/cache/nginx
    - /opt/site/webroot:/webroot/:ro

  acmesh:
    container_name: acmesh
    image: neilpang/acme.sh
    volumes:
      - /data/acmesh/certs:/acme.sh
    command: daemon
    network_mode: host

  mongo:
    command: mongod --directoryperdb
    container_name: mongo
    hostname: mongo
    image: library/mongo:7.0.1
    logging:
      options:
        max-size: 10m
    network_mode: host
    restart: always
    volumes:
    - /data/mongo/data:/data/db
    - /data/mongo-import:/import

  sklenikomil:
    image: elinit/sklenikomil:v1.0
    container_name: sklenikomil
    network_mode: host
    volumes:
    - /opt/site/sklenikomil/conf:/conf:ro